### PR TITLE
Convert syntax to sublime-syntax instead of tmLanguage.

### PR DESCRIPTION
**Pull request by schneidmaster**
* What: Converts `.tmLanguage` syntax file into the new `.sublime-syntax` format. No other changes in this PR; should match up exactly.

* Why: `.sublime-syntax` is newer and allows for [richer syntax highlighting and better performance](https://www.sublimetext.com/blog/articles/sublime-text-3-build-3103)

* Testing: Check out branch, copy `syntax/CJSX.sublime-syntax` to your Sublime Text packages folder, open a CJSX file in Sublime, and use the command palette to select the new syntax.

### CODE REVIEW

**Comment by cooncesean** [comment]
Sounds great (ty for the contribution). 

What does backwards compatibility look like?

**Comment by schneidmaster** [comment]
`.sublime-syntax` was introduced in Build 3103 on 9 February 2016, so it doesn't work in older Sublime 3 or Sublime 2. ST3 shouldn't be an issue since Sublime auto-updates so I doubt anyone is using builds of ST3 from a year ago.

I can understand if you don't want to drop ST2 support -- I would argue that it's worth it though:

* ST2 was last updated 8 July 2013
* At least anecdotally, I have been using ST3 full-time since early 2014
* ST3 has been the "recommended" version (the version you get from the CTA on the ST homepage) for about a year now

**Comment by cooncesean** [comment]
Apologies for the delay on this @schneidmaster.

Can you do me one favor and update the base `README.md` file with a section at the top that states the Sublime versions supported by the library (once these changes are merged)? One or two quick sentences should suffice as well as a link to the commit before your commit that points people in the right direction if they're still using an older version of Sublime.

Get that changed and we'll get this merged.

Thanks for all of the help 👍

**Comment by schneidmaster** [comment]
No problem, thanks for reviewing. I added a note to the README and rebased back down to one commit again. Let me know if you'd like any changes.

**Comment by schneidmaster** [comment]
Thanks for merging. You may also wish to send a PR to [package control](https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L1058-L1068) to indicate that the package now only supports ST3 (change `"sublime_text": "*"` to `"sublime_text": ">=3103"`). I'd do it but it might get rejected since I'm not the repository owner.

**Pull request merged**
